name: Generate List

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install bgpstuff

      - name: Create output file
        id: generate_output
        run: |
          output=$(python generate_list.py)
          echo "::set-output name=result::$output"

      - name: Save output to file
        run: echo "${{ steps.generate_output.outputs.result }}" > output.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "charles.allen@zagg.com"
          git config --global user.name "Charles Allen"
          git add output.txt
          git commit -m "Generate list"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}